version: '3'

services:

  web:
    build: ../olx-clone
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - network-backend
  api:
    build: ../olx-clone-api
    depends_on:
      - db
    ports:
      - "3001:3001"
    networks:
      - network-backend
  db:
    image: postgres:15.1
    container_name: postgresql
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST=host.docker.internal
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - db:/var/lib/postgresql/data
  db-manage:
    image: dpage/pgadmin4
    container_name: postgres-pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "80:80"

networks:
  network-backend:

volumes:
  db:
    driver: local